name: "Auto Generate Next Release Tag"
description: "Automatically generate next release tag incrementally with date/month/year and based on previous tag."
author: "amitsingh-007"
branding:
  color: "red"
  icon: "tag"

inputs:
  github_token:
    description: "Github secrets token"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
